# -*- coding: utf-8 -*-
"""question_answering_1_0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/199V9daFLLmKzR-YnFyDVOYeP3eNoBRac

**Text extraction using PyPDF2**


---
"""

!pip install PyPDF2

import PyPDF2

# Open the PDF file in read-binary mode
with open('sample (3).pdf', 'rb') as file:
    # Create a PDF reader object
    reader = PyPDF2.PdfReader(file)

    # Extract text from each page
    text = ''
    for page in reader.pages:
        lines = page.extract_text().split('\n')
        filtered_lines = lines[2:-1]  # Exclude the first two and last lines
        filtered_text = '\n'.join(filtered_lines)
        text += filtered_text + "\n\n"

# Print the extracted text
print("**************")
print(text)

"""**Question answering Transformers**

"""

!pip install transformers

from transformers import pipeline

nlp = pipeline("question-answering")

result = nlp(question="what are the components of Job management?", context=text)
print(result)

result = nlp(question="what is SAP solution manager?", context=text)
print(result['answer'])

result = nlp(question="what can you monitor with SAP Solution Manager?", context=text)
print(result['answer'])

result = nlp(question="what is job monitoring?", context=text)
print(result['answer'])